test("...")
...
command(0, 78) # <===
expect("...")
... # output generated by this command
expect("@timestamp Trg-Done QS_RX_COMMAND")

command("MY_CMD", 123, 456, 789) # <===
... # output generated by this command
expect("@timestamp Trg-Done QS_RX_COMMAND")

